---
fuse_namespace: "{{ eval_managed_fuse_namespace }}"
fuse_cr_name: fuse-managed
fuse_backup_postgres_secret_name: fuse-postgres-auth

fuse_pull_secret_name: "syndesis-pull-secret"

fuse_resources: []

fuse_image_streams:
  - jboss-amq-63:1.3
  - syndesis-operator:{{ fuse_online_operator_imagestream_version }}
  - syndesis-s2i:{{ fuse_online_operator_imagestream_version }}

fuse_heimdall_exclude_pattern: "todo"
